# Generated by Django 2.2.13 on 2020-08-12 17:04

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def update_invoice_items_scope(apps, schema_editor):
    InvoiceItem = apps.get_model('invoices', 'InvoiceItem')
    Resource = apps.get_model('marketplace', 'Resource')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    SupportOffering = apps.get_model('support', 'Offering')

    for invoice_item in InvoiceItem.objects.filter(
        content_type_id=ContentType.objects.get_for_model(SupportOffering).id
    ):
        try:
            resource = Resource.objects.get(
                content_type_id=ContentType.objects.get_for_model(SupportOffering).id,
                object_id=invoice_item.object_id,
            )
            invoice_item.content_type_id = ContentType.objects.get_for_model(
                Resource
            ).id
            invoice_item.object_id = resource.id
            invoice_item.save()
        except ObjectDoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_offeringpermission'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('invoices', '0040_invoice_created'),
        ('support', '0010_error_traceback'),
    ]

    operations = [
        migrations.RunPython(update_invoice_items_scope),
    ]
